# Generated by Django 3.2.9 on 2021-12-28 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_userinfo_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='id',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='uid',
            field=models.CharField(default=1, max_length=32, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
